### ISSUE TITLE
Missing prompts in prompt/prompt.py!

### ISSUE THREAD

**Issue by BingliangLi** [WilliamZR/ProTrix#2]
from prompt.plan_and_sql import PLAN_PROMPT
from prompt.reason import REASON_PROMPT
from prompt.one_step import ONE_STEP_PROMPT
from prompt.reason_after_sql import REASON_AFTER_SQL_PROMPT
from prompt.extract_answer import EXTRACT_ANSWER_PROMPT

**Comment by WilliamZR** [comment]
Hi Bingliang,

Thanks for your interest in our work. The missing prompts are for another prompt setting and we did not upload those prompts since we do not use them to generate the answers. We appreciate you pointing out this issue. I have removed the unused prompt settings from our code to avoid confusion.

If you have any other questions, feel free to contact us.

Cheers,
Zirui
